### ISSUE TITLE
Regression target normalization

### ISSUE THREAD

**Issue by dkoguciuk** [zylo117/Yet-Another-EfficientDet-Pytorch#114]
Hi @zylo117 ,

I've seen that in [f833223](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/f833223fa6687e0062924d4d649a80d9107622e4#diff-34fc60f6e9f3fced47a7a4b622abc0c0L128) you've removed regression target normalization. Could you please elaborate what's the intuition behind it?

Best,
Daniel

**Comment by zylo117** [comment]
because i adapted official anchor decoder to this repo. However this anchor decoder takes different parameters of anchor ratios. In order to avoid bugs, i adapted the decoding method into the encoding in focalloss instead of re-introducing normalization over TF's method.

In short, TF version doesn't apply normalization on target, so does this repo.
