### ISSUE TITLE
how to reduce the false prediction?

### ISSUE THREAD

**Issue by zizizihua** [zylo117/Yet-Another-EfficientDet-Pytorch#138]
I got high map on my dataset, but when I put an image that there is no target, the prediction still contains a few bbox with high score confidence. Even though I added some negtive samples for training, twenty percent of total image number, the result almost has no difference. How to reduce the false prediction effectively?

**Comment by zylo117** [comment]
hi, that's hardly possible for anchor detection network like yolo and efficientdet.

because there is no background class. these kinds of network wouldn't learn from background.

you can set a higher threshold to avoid the false positive boxes or try RCNN which can separate foreground from the background.

**Comment by zizizihua** [comment]
@zylo117 okay, thanks for your suggestion. I'll try it.
