### ISSUE TITLE
A problem about Conv2dStaticSamePadding and MaxPool2dStaticSamePadding

### ISSUE THREAD

**Issue by poirotZhu** [zylo117/Yet-Another-EfficientDet-Pytorch#519]
Hello, 
As I know, when you use Conv2dStaticSamePadding and MaxPool2dStaticSamePadding, you should compute all the parameters in the init funtion. So i think you should move the following codes 
```<Python>
h, w = x.shape[-2:]
extra_h = (math.ceil(w / self.stride[1]) - 1) * self.stride[1] - w + self.kernel_size[1]
extra_v = (math.ceil(h / self.stride[0]) - 1) * self.stride[0] - h + self.kernel_size[0]
left = extra_h // 2
right = extra_h - left
top = extra_v // 2
bottom = extra_v - top
```
to the init function. Otherwise when you export the model to the onnx format, you will get an error.

**Comment by zylo117** [comment]
Well, but your solution is not always right. For example, the same conv module can forward differernt X, right? If the first X is 512, 512 and the second X is 513, 513 and the padding remains the same since padding size is determined during `__init__`, there will be exception.
Though it shouldn't happen in this repo.

**Comment by poirotZhu** [comment]
Yes, you're right. I think you should use dyanmicpadding in training and staticpadding when you want to export the model.
