### ISSUE TITLE
BN not shared in classifier/regressor

### ISSUE THREAD

**Issue by rvandeghen** [zylo117/Yet-Another-EfficientDet-Pytorch#560]
Hi, I was wondering why do you change the BN depending on the pyramid level for the classifier/regressor subnets.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/1b0fdfe65e366733639478766f2660ea853d13f0/efficientdet/model.py#L392
For me, nothing in the TF implementation induces it: https://github.com/google/automl/blob/64bb0e083581ba731ee1fa85c6456e60e6f09abc/efficientdet/efficientdet_arch.py#L136

If I'm right, I'll correct the init and forward functions accordingly in a PR.

Renaud

**Comment by zylo117** [comment]
hahaha. good question. that's a very tricky one.

I did mention it in my readme though, in FAQ A2, point 8.

In the original repo,

https://github.com/google/automl/blob/64bb0e083581ba731ee1fa85c6456e60e6f09abc/efficientdet/efficientdet_arch.py#L178

There is a variable `level` there to choose to the specified BN layer to operate.

Back then, it took me a moment to realize why can't I get the same result like they did.

**Comment by rvandeghen** [comment]
@zylo117 I've missed it, but you're right it's tricky.
However, have you noticed that your implementation has some conflicts with the EfficientNet one when loading only pretained of EffNet.
Since your implementation of `Conv2dStaticSamePadding` is a `nn.Module` and not a `nn.Conv2d`, the state dict for the backbone is all different since it now uses your implementation.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/1b0fdfe65e366733639478766f2660ea853d13f0/efficientnet/utils.py#L103
I have made the changes on my local version but I think it can be useful to also correct it here.

**Comment by zylo117** [comment]
I know that but it's a little bit too late to change since many people including me are using this version. There is no need to change this implementation, considering those two are almost the same thing.

But it's possible to adapt the efficientnet's weights loading part to my conv2d module, by changing the names of conv's weight and bias.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/1b0fdfe65e366733639478766f2660ea853d13f0/efficientnet/utils.py#L299

**Comment by rvandeghen** [comment]
As far as you are aware I'm fine :)
