### ISSUE TITLE
What is the processing strategy for large images?

### ISSUE THREAD

**Issue by wizardk** [zylo117/Yet-Another-EfficientDet-Pytorch#91]
@zylo117 Hi, thanks for your contribution and I must to say that your repo is really clear and nice.

I have a question about large images.
Since the images are very large in my dataset(5K*4K) and resizing them to small images is not reasonable, in the training time, I selected one random crop which include part of targets in one image.
In the inferring time, it'll consume huge memory if I input the whole image.
Do you have good advice about the inferring strategy for these large images?

**Comment by zylo117** [comment]
it depends on whether the object proportion is big enough to match the anchors. 

the smallest anchor should be 32x32. If the objects proportion are at least greater than 32^2 / 512^2 (assuming you are training d0), then it's ok to resize them, otherwise, you have to input the larger image so that the minimum object area is bigger than 32x32.

**Comment by wizardk** [comment]
Thanks.
